---
version: 0.2
phases:

  

  pre_build:
      commands:
        - $(aws ecr get-login --no-include-email)  
        - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)


  build:
    commands:
      - docker build -t $DATETIME_REPOSITORY_URI:$COMMIT_HASH .


  post_build:
    commands:
      - docker push $DATETIME_REPOSITORY_URI:$COMMIT_HASH


      - printf '{"ImageURI":"%s:%s"}' $DATETIME_REPOSITORY_URI $COMMIT_HASH > imageDetail.json

artifacts:
  files:
    - imageDetail.json
 